/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BattleRecord {
  'playerIds' : Array<string>,
  'winnerId' : string,
  'userId' : string,
  'scores' : Array<[string, bigint]>,
  'mode' : string,
  'timestamp' : bigint,
}
export interface CodingProblem {
  'id' : string,
  'moduleId' : bigint,
  'title' : string,
  'xpReward' : bigint,
  'hint' : string,
  'description' : string,
  'brokenCode' : string,
  'solutionKeyword' : string,
}
export interface LeaderboardEntry {
  'xp' : bigint,
  'username' : string,
  'userId' : string,
}
export interface McqQuestion {
  'id' : string,
  'moduleId' : bigint,
  'correctOption' : string,
  'question' : string,
  'xpReward' : bigint,
  'hint' : string,
  'optionA' : string,
  'optionB' : string,
  'optionC' : string,
  'optionD' : string,
}
export interface Module {
  'id' : string,
  'theme' : string,
  'icon' : string,
  'name' : string,
  'description' : string,
}
export type Result = { 'ok' : bigint } |
  { 'err' : string };
export type Result_1 = {
    'ok' : { 'correct' : boolean, 'message' : string, 'xpEarned' : bigint }
  } |
  { 'err' : string };
export type Result_2 = { 'ok' : { 'correct' : boolean, 'score' : bigint } } |
  { 'err' : string };
export type Result_3 = { 'ok' : string } |
  { 'err' : string };
export type Result_4 = { 'ok' : UserProfile } |
  { 'err' : string };
export type Result_5 = { 'ok' : BattleRecord } |
  { 'err' : string };
export type Result_6 = {
    'ok' : { 'message' : string, 'xpEarned' : bigint, 'passed' : boolean }
  } |
  { 'err' : string };
export interface UserProfile {
  'xp' : bigint,
  'completedWorlds' : Array<string>,
  'username' : string,
  'userId' : string,
  'level' : bigint,
  'achievements' : Array<string>,
  'battleWins' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkCode' : ActorMethod<[string, string, string], Result_6>,
  'completeBattle' : ActorMethod<[string], Result_5>,
  'createBattle' : ActorMethod<[string, string], Result_5>,
  'getAiHint' : ActorMethod<[string], Result_3>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCodingProblems' : ActorMethod<[string], Array<CodingProblem>>,
  'getLeaderboard' : ActorMethod<[[] | [string]], Array<LeaderboardEntry>>,
  'getMcqQuestions' : ActorMethod<[string], Array<McqQuestion>>,
  'getModules' : ActorMethod<[], Array<Module>>,
  'getProfile' : ActorMethod<[string], Result_4>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinBattle' : ActorMethod<[string, string], Result_5>,
  'loginUser' : ActorMethod<[string, string], Result_4>,
  'registerUser' : ActorMethod<[string, string, string], Result_3>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBattleAnswer' : ActorMethod<
    [string, string, string, bigint],
    Result_2
  >,
  'submitMcqAnswer' : ActorMethod<[string, string, string], Result_1>,
  'updateXP' : ActorMethod<[string, bigint], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];