/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_6 = IDL.Variant({
  'ok' : IDL.Record({
    'message' : IDL.Text,
    'xpEarned' : IDL.Nat,
    'passed' : IDL.Bool,
  }),
  'err' : IDL.Text,
});
export const BattleRecord = IDL.Record({
  'playerIds' : IDL.Vec(IDL.Text),
  'winnerId' : IDL.Text,
  'userId' : IDL.Text,
  'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'mode' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Result_5 = IDL.Variant({ 'ok' : BattleRecord, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UserProfile = IDL.Record({
  'xp' : IDL.Nat,
  'completedWorlds' : IDL.Vec(IDL.Text),
  'username' : IDL.Text,
  'userId' : IDL.Text,
  'level' : IDL.Nat,
  'achievements' : IDL.Vec(IDL.Text),
  'battleWins' : IDL.Nat,
});
export const CodingProblem = IDL.Record({
  'id' : IDL.Text,
  'moduleId' : IDL.Nat,
  'title' : IDL.Text,
  'xpReward' : IDL.Nat,
  'hint' : IDL.Text,
  'description' : IDL.Text,
  'brokenCode' : IDL.Text,
  'solutionKeyword' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'xp' : IDL.Nat,
  'username' : IDL.Text,
  'userId' : IDL.Text,
});
export const McqQuestion = IDL.Record({
  'id' : IDL.Text,
  'moduleId' : IDL.Nat,
  'correctOption' : IDL.Text,
  'question' : IDL.Text,
  'xpReward' : IDL.Nat,
  'hint' : IDL.Text,
  'optionA' : IDL.Text,
  'optionB' : IDL.Text,
  'optionC' : IDL.Text,
  'optionD' : IDL.Text,
});
export const Module = IDL.Record({
  'id' : IDL.Text,
  'theme' : IDL.Text,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Result_4 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
export const Result_2 = IDL.Variant({
  'ok' : IDL.Record({ 'correct' : IDL.Bool, 'score' : IDL.Nat }),
  'err' : IDL.Text,
});
export const Result_1 = IDL.Variant({
  'ok' : IDL.Record({
    'correct' : IDL.Bool,
    'message' : IDL.Text,
    'xpEarned' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_6], []),
  'completeBattle' : IDL.Func([IDL.Text], [Result_5], []),
  'createBattle' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'getAiHint' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCodingProblems' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CodingProblem)],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMcqQuestions' : IDL.Func([IDL.Text], [IDL.Vec(McqQuestion)], ['query']),
  'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getProfile' : IDL.Func([IDL.Text], [Result_4], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinBattle' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [Result_4], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_3], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBattleAnswer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [Result_2],
      [],
    ),
  'submitMcqAnswer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_1], []),
  'updateXP' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_6 = IDL.Variant({
    'ok' : IDL.Record({
      'message' : IDL.Text,
      'xpEarned' : IDL.Nat,
      'passed' : IDL.Bool,
    }),
    'err' : IDL.Text,
  });
  const BattleRecord = IDL.Record({
    'playerIds' : IDL.Vec(IDL.Text),
    'winnerId' : IDL.Text,
    'userId' : IDL.Text,
    'scores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'mode' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Result_5 = IDL.Variant({ 'ok' : BattleRecord, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserProfile = IDL.Record({
    'xp' : IDL.Nat,
    'completedWorlds' : IDL.Vec(IDL.Text),
    'username' : IDL.Text,
    'userId' : IDL.Text,
    'level' : IDL.Nat,
    'achievements' : IDL.Vec(IDL.Text),
    'battleWins' : IDL.Nat,
  });
  const CodingProblem = IDL.Record({
    'id' : IDL.Text,
    'moduleId' : IDL.Nat,
    'title' : IDL.Text,
    'xpReward' : IDL.Nat,
    'hint' : IDL.Text,
    'description' : IDL.Text,
    'brokenCode' : IDL.Text,
    'solutionKeyword' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'xp' : IDL.Nat,
    'username' : IDL.Text,
    'userId' : IDL.Text,
  });
  const McqQuestion = IDL.Record({
    'id' : IDL.Text,
    'moduleId' : IDL.Nat,
    'correctOption' : IDL.Text,
    'question' : IDL.Text,
    'xpReward' : IDL.Nat,
    'hint' : IDL.Text,
    'optionA' : IDL.Text,
    'optionB' : IDL.Text,
    'optionC' : IDL.Text,
    'optionD' : IDL.Text,
  });
  const Module = IDL.Record({
    'id' : IDL.Text,
    'theme' : IDL.Text,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Result_4 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const Result_2 = IDL.Variant({
    'ok' : IDL.Record({ 'correct' : IDL.Bool, 'score' : IDL.Nat }),
    'err' : IDL.Text,
  });
  const Result_1 = IDL.Variant({
    'ok' : IDL.Record({
      'correct' : IDL.Bool,
      'message' : IDL.Text,
      'xpEarned' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkCode' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_6], []),
    'completeBattle' : IDL.Func([IDL.Text], [Result_5], []),
    'createBattle' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'getAiHint' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCodingProblems' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CodingProblem)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMcqQuestions' : IDL.Func([IDL.Text], [IDL.Vec(McqQuestion)], ['query']),
    'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getProfile' : IDL.Func([IDL.Text], [Result_4], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinBattle' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [Result_4], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_3], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBattleAnswer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [Result_2],
        [],
      ),
    'submitMcqAnswer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'updateXP' : IDL.Func([IDL.Text, IDL.Nat], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };